freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  matrix:
    - name: cargo test (nightly)
      env:
        VERSION: +nightly
    - name: cargo test (1.44.0)
      env:
        VERSION: +1.44.0
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo $VERSION build $CARGO_ARGS --all
