[package]
name = "freebsd-nfs-exporter"
description = "Prometheus exporter for FreeBSD NFS stats"
version = "0.3.0"
authors = ["Alan Somers <asomers@axcient.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/Axcient/freebsd-nfs-exporter.git"
keywords = ["prometheus", "monitoring", "nfs", "freebsd"]
exclude = [
    "/.gitignore",
    "bindgen.*"
]

[[bin]]
name = "nfs-exporter"
path = "src/main.rs"

[dependencies]
clap = "2.0"
env_logger = "0.7"
prometheus_exporter = "0.6"
